include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

variables:
  SAST_EXCLUDED_PATHS: 'spec, test, tests, tmp, lib'

.nodestuff: &nodestuff
  image: node:lts-alpine
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules

install:
  stage: build
  script:
    - npm install
    - npm pack
  artifacts:
    paths:
      - ./lib/*.js
      - ./*.tgz
  <<: *nodestuff

test:
  stage: test
  needs:
    - install
  script:
    - npm run test -- --reporter mocha-junit-reporter
  artifacts:
    reports:
      junit: test-results.xml
  <<: *nodestuff

publish:
  stage: deploy
  needs:
    - install
    - test
    - eslint-sast
    - nodejs-scan-sast
    - semgrep-sast
    - gemnasium-dependency_scanning
    - retire-js-dependency_scanning
    - secret_detection
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - cat "//registry.npmjs.org/:_authToken=$VAR_NPM_AUTHTOKEN" > ~/.npmrc
    - npm publish
  <<: *nodestuff


